trigger:
- main

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@1

  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure-cpg-test'
    backendAzureRmResourceGroupName: 'cpg-dnd'
    backendAzureRmStorageAccountName: 'cpgdnd8911'
    backendAzureRmContainerName: 'azure-webjobs-hosts'
    backendAzureRmKey: 'UD~8Q~jMYSV3n5U_Er~VIaTwSBn4JhSfVAy~XcQs'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: 'input:false'
    environmentServiceNameAzureRM: 'azure-cpg-test'


- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: 'input:false'
    environmentServiceNameAzureRM : 'azure-cpg-test'
